MorralViajero/urls.py
from django.conf.urls import url,include
from django.contrib import admin

from main import urls as UrlMain
from travels import urls as UrlTravel
from blog import urls as UrlBlog

from django.views.static import serve
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(UrlMain, namespace="main")),
    url(r'^', include(UrlTravel, namespace="travel")),
    url(r'^blog/', include(UrlBlog, namespace="blog")),
    #Url para media
    url(
    	regex=r'^media/(?P<path>.*)$',
    	view=serve,
    	kwargs = {'document_root':settings.MEDIA_ROOT}),
]

blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.PostList.as_view(), name='post_list'),
	url(r'^tag/(?P<tag_slug>[-\w]+)/$', views.PostList.as_view(), name="post_list_by_tag"),
	url(r'^list/$', views.PostListView.as_view(), name='post_list_view'),
	url(r'^(?P<post>[-\w]+)/$', views.PostDetailView.as_view(), name="post_detail"),
	url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$', views.PostDetail.as_view(), name="post_detail"),
	url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/(?P<ready>\d+)/$', views.PostDetail.as_view(), name="post_detail_ready"),
	url(r'^(?P<post_id>\d+)/share/$', views.SentEmailView.as_view(), name="post_share"),
	url(r'^(?P<post_id>\d+)/(?P<conf>\d+)/share/$', views.SentEmailView.as_view(), name="post_share_conf"),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.conf import settings
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
	def get_queryset(self):
		return super(PublishedManager, self).get_queryset().filter(status='published')

# Create your models here.
class Post(models.Model):
	STATUS_CHOICES = (('draft', 'Borrador'), ('published', 'Publicado'))
	title = models.CharField(max_length=250)
	slug = models.SlugField(max_length=250, unique_for_date='publish')
	author = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='blog_posts')
	body = models.TextField()
	portada = models.ImageField(upload_to='portada-post', blank=True,null=True)
	image_card = models.ImageField(upload_to='card_post', blank=True, null=True)
	publish = models.DateTimeField(default=timezone.now)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
	objects = models.Manager()
	published = PublishedManager()
	tags = TaggableManager()

	class Meta:
		ordering = ('-publish',)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('blog:post_detail',args = [self.slug])

class Comment(models.Model):
	post = models.ForeignKey(Post, related_name="comments")
	name = models.CharField(max_length=80)
	email = models.EmailField()
	body = models.CharField(max_length=150)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	active = models.BooleanField(default=True)

	class Meta:
		ordering = ('created',)

	def __str__(self):
		return 'Comentado por {} en {}'.format(self.name, self.post)

blog/forms.py
from django import forms
from pagedown.widgets import PagedownWidget
from .models import Comment

class EmailPostForm(forms.Form):
	nombre = forms.CharField(max_length=25, label="", widget=forms.TextInput(attrs={'class':'form-control',
		'type':'text',
		'placeholder':'Nombre...'}))
	correo = forms.EmailField(label="", widget=forms.TextInput(attrs={'class':'form-control',
		'type':'email',
		'placeholder':'Correo...'}))
	para = forms.EmailField(label="", widget=forms.TextInput(attrs={'class':'form-control',
		'type':'email',
		'placeholder':'Para...'}))
	comentarios = forms.CharField(label="", required=False, widget=forms.Textarea(attrs={'class':'form-control',
		'type':'text',
		'placeholder':'Comentarios...',
		'rows':'3',}))

class CommentForm(forms.ModelForm):
	name = forms.CharField(max_length=80, label="", widget=forms.TextInput(attrs={'class':'form-control',
		'type':'text',
		'placeholder':'Nombre...'}))
	email = forms.EmailField(label="", widget=forms.TextInput(attrs={'class':'form-control',
		'type':'email',
		'placeholder':'Correo...'}))
	body = forms.CharField(max_length=150, label="", widget=forms.Textarea(attrs={'class':'form-control',
		'type':'text',
		'placeholder':'Comentario..',
		'rows':'3',}))
	#body = forms.CharField(widget=PagedownWidget(show_preview= False,attrs={'class':'form-control',
	#	'type':'text',
	#	'label':'',
	#	'placeholder':'Comentar Publicación...',
	#	'rows':'3',}))
	
	class Meta:
		model = Comment
		fields=('name', 'email', 'body')

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.urlresolvers import reverse
from django.views.generic import View, ListView
from .models import Post, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import EmailPostForm, CommentForm

#Para el envio de Email
from django.core.mail import send_mail

#Taggit
from taggit.models import Tag

from django.db.models import Count

# Create your views here.

# Enviar Email 
class SentEmailView(View):
	def get(self, request, post_id, conf=None):
		sent = False
		template_name = 'blog/share.html'
		post = get_object_or_404(Post, id=post_id, status='published')
		form = EmailPostForm()
		if conf:
			if conf == '1':
				sent = True
		context = {
			'form':form,
			'post':post,
			'sent':sent,
		}
		return render(request, template_name, context)

	def post(self, request, post_id):
		template_name = 'blog/share.html'	
		post = get_object_or_404(Post, id=post_id, status='published')
		sent = False
		form = EmailPostForm(request.POST)
		if form.is_valid():
			cd = form.cleaned_data
			##Obtener el url de nuestro post
			post_url = request.build_absolute_uri(post.get_absolute_url())
			subject = '{} ({}) te recomienda leer "{}"'.format(cd['nombre'], cd['correo'], post.title)
			message = 'Leer "{}" de {}\n\n comentarios de {}: {}'.format(post.title, post_url, cd['nombre'], cd['comentarios'])
			send_mail(subject, message, 'admin@my_blog.com', [cd['para']])
			sent = True
			conf = 1
			return redirect('blog:post_share_conf', post.id, conf)
			# ... enviando email
		else:
			form = EmailPostForm()
		context = {
			'post':post,
			'form':form,
			'sent:':sent,
		}
		return render(request, template_name, context)

class PostList(View):
	def get(self, request, tag_slug=None):
		template_name = "blog/post_list.html"
		# object_list = Post.published.all()
		object_list = Post.objects.order_by('title')
		#taggit
		tag = None
		if tag_slug:
			tag = get_object_or_404(Tag, slug=tag_slug)
			object_list = object_list.filter(tags__in=[tag])
		paginator = Paginator(object_list, 8) #6 post en cada pagina
		page = request.GET.get('page')
		try:
			posts = paginator.page(page)
		except PageNotAnInteger:
			posts = paginator.page(1)
		except EmptyPage:
			posts = paginator.page(paginator.num_pages)
		context = {
			'page':page,
			'posts':posts,
			'tag':tag,
		}
		return render(request, template_name, context)

class PostListView(ListView):
	queryset = Post.published.all()
	context_object_name = 'posts'
	paginate_by = 3
	template_name = 'blog/post_list_view.html'

class PostDetail(View):
	def get(self, request, year, month, day, post, ready = None):
		if ready:
			if ready == '1':
				ready = True
		template_name = "blog/post_detail.html"
		post = get_object_or_404(Post, slug=post,
			status = 'published',
			publish__year = year,
			publish__month = month,
			publish__day = day,)
		comments = post.comments.filter(active=True)
		comment_form = CommentForm()
		post_tags_ids = post.tags.values_list('id', flat=True)
		similar_posts = Post.published.filter(tags__in = post_tags_ids).exclude(id=post.id)
		similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]
		context = {
			'post':post,
			'comments':comments,
			'comment_form': comment_form,
			'ready':ready,
			'similar_posts':similar_posts,
		}
		return render(request, template_name, context)

	def post(self, request, year, month, day, post):
		ready = False
		post = get_object_or_404(Post, slug=post,
			status = 'published',
			publish__year = year,
			publish__month = month,
			publish__day = day,)
		comments = post.comments.filter(active=True)
		comment_form = CommentForm(data=request.POST)
		if comment_form.is_valid():
			new_comment = comment_form.save(commit=False)
			new_comment.post = post
			new_comment.save()
			ready = 1
			return redirect('blog:post_detail_ready', post.publish.year, post.publish.strftime('%m'), post.publish.strftime('%d'), post.slug, ready)
		else:
			comment_form = ()
		post_tags_ids = post.tags.values_list('id', flat=True)
		similar_posts = Post.published.filter(tags__in = post_tags_ids).exclude(id=post.id)
		similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]
		context = {
			'post':post,
			'comments':comments,
			'comment_form': comment_form,
			'ready':ready,
			'similar_posts':similar_posts
		}
		return render(request, template_name, context)

class PostDetailView(View):
	def get(self, request, post, ready = None):
		if ready:
			if ready == '1':
				ready = True
		template_name = "blog/post_detail.html"
		post = get_object_or_404(Post, slug=post,
			status = 'published',)
		comments = post.comments.filter(active=True)
		comment_form = CommentForm()
		post_tags_ids = post.tags.values_list('id', flat=True)
		similar_posts = Post.published.filter(tags__in = post_tags_ids).exclude(id=post.id)
		similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]
		context = {
			'post':post,
			'comments':comments,
			'comment_form': comment_form,
			'ready':ready,
			'similar_posts':similar_posts,
		}
		return render(request, template_name, context)

blog/templates/blog/latest_posts.html
{% load blog_tags %}
{% load static %}
    <div class="row justify-content-center">
      <div class="col-lg-8 text-center">
        <h2 class="display-3">#BlogMorralViajero</h2>
        <p class="lead text-muted">Entradas recientes...</p>
      </div>
      <div class="col-lg-12">
        <div class="row row-grid">
        {% for post in latest_posts %}
          <div class="col-lg-3">
            <div class="card card-lift--hover shadow border-0">
              <div class="card-header">
              	<img src="{% if post.image_card %}{{post.image_card.url}}{%else%}{%static 'img/brand/Logo-morral-1.png'%}{%endif%}"  class="img-fluid">
              </div>
              <div class="card-body py-5">
                <h6 class="text-warning text-uppercase">{{post.title}}</h6>
                <p class="description mt-3">{{post.body|truncatewords_html:5}}</p>
                <div>
                  <span class="badge badge-pill badge-warning"><i class="fas fa-pen"></i> {{post.author}}</span>
                </div>
                <a href="{{ post.get_absolute_url }}" class="btn btn-warning mt-4">Leer</a>
              </div>
            </div>
          </div>
        {% endfor %}
        </div>
      </div>
    </div>

blog/templates/blog/pagination.html
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-end">
    {% if page.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.previous_page_number }}">
        <i class="fa fa-angle-left"></i>
        <span class="sr-only">Anterior</span>
      </a>
    </li>
    {%endif%}
    <li class="page-item active"><a class="page-link" href="#">{{ page.number }} </a></li>
    <li class="page-item disabled"><a class="page-link" href="#">de </a></li>
    <li class="page-item"><a class="page-link" href="#">{{ page.paginator.num_pages}} </a></li>
    {% if page.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.next_page_number }}">
        <i class="fa fa-angle-right"></i>
        <span class="sr-only">Siguiente</span>
      </a>
    </li>
    {%endif%}
  </ul>
</nav>

blog/templates/blog/post_detail.html
{% extends 'base.html'%}
{% load static%}
{% load blog_tags %}



{% block head %}
    <!--Facebook-->
    <!-- You can use open graph tags to customize link previews.
    Learn more: https://developers.facebook.com/docs/sharing/webmasters -->
    <meta property="og:url"           content="{{request.build_absolute_uri}}" />
    <meta property="og:type"          content="article" />
    <meta property="og:title"         content="{{ post.title }}" />
    <meta property="og:description"   content="{{ post.body}}" />
    <meta property="og:image"         content="{{ post.portada.url}}" />




{% endblock head %}

{% block title %}
	{{ post.title }}
{% endblock title %}

{% block content %} 

  <section class="blog_d view" style="background-image: url({{ post.portada.url}}); padding-top:100px;">
    <div class="container text-center" style="padding: 70px;">
        <div class="col-lg-12 text-lg-center btn-wrapper text-center">
          <h2 class="text-white text-uppercase">COMPARTIR<h2>
          <!--<div class="fb-share-button" data-href="{{request.build_absolute_uri}}" data-layout="box_count" data-size="large" data-mobile-iframe="true"><a class="fb-xfbml-parse-ignore" target="_blank">Compartir</a>-
          </div>-->
           <a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u={{request.build_absolute_uri}}" class="btn btn-neutral btn-icon-only btn-facebook btn-round btn-lg" data-toggle="tooltip" data-original-title="shared on Facebook">
            <i class="fab fa-facebook"></i>
          </a>

          <a target="_blank" href="https://twitter.com/home?status=%23SinExcusasParaViajar%20@MorralViajero%20{{request.build_absolute_uri}}" class="btn btn-neutral btn-icon-only btn-twitter btn-lg btn-round" data-toggle="tooltip" data-original-title="Shared on Twitter">
            <i class="fab fa-twitter"></i>
          </a>
         
          <a target="_blank" href="https://plus.google.com/share?url={{request.build_absolute_uri}}" class="btn btn-neutral btn-icon-only btn-google-plus btn-round btn-lg" data-toggle="tooltip" data-original-title="Shared on Google +">
            <i class="fab fa-google-plus-g"></i>
          </a>

          <a target="_blank" href="https://wa.me/?text={{request.build_absolute_uri}}%20" class="btn btn-neutral btn-icon-only btn-whatsapp btn-round btn-lg" data-toggle="tooltip" data-original-title="Shared on Whatsapp">
            <i class="fab fa-whatsapp"></i>
          </a>
        </div>
    </div>
  </section>

  <section>
    <div class="container" style="padding-top:20px;">
      <div class="row">
        <div class="col-lg-2">
          <a href="{% url 'blog:post_list' %}"><p><i class="fa fa-arrow-left" aria-hidden="true"></i> Lista de post</p></a>
        </div>
        <div class="col-lg-8 content-markdown content-justify">
          <h1 class="display-1">{{ post.title }}</h1>
          <p class="text-red"><i class="fas fa-calendar-alt"></i> {{ post.publish|date:"d/M/Y" }} , <i class="far fa-user"></i> {{ post.author }}.</p>
          {{post.body|markdown}}
        </div> 
      </div>
    </div>
  </section>




{% endblock content %}

{% block scripts %}
  
{% endblock scripts %}

blog/templates/blog/post_list.html
{% extends 'base.html'%}
{%load static%}
{% load blog_tags %}

{% block title %}
	Blog
{% endblock title %}
{%block head%}
	
{%endblock head%}
{%block header%}

{%endblock header%}
{% block content %}
    <div class="position-relative">
      <!-- shape Hero -->
      <section class="section-shaped my-0">
        <div class="shape shape-style-1 shape-default-blog shape-skew">
          <span></span>
          <span></span>
          <span></span>
          <span></span>
          <span></span>
          <span></span>
          <span></span>
          <span></span>
          <span></span>
          <span></span>
          <span></span>
          <span></span>
          <span></span>
        </div>
        <div class="container shape-container d-flex">
          <div class="col px-0">
            <div class="row">
              <div class="col-lg-6">
                <p class="lead">
                <br>
                </p>
                <h2 class="display-4" style="color: #fff;"><span>#BlogMorralViajero</span></h2>
                <br>
                <br>
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>
      <!-- 1st Hero Variation -->
    </div>

    <section class="section section-lg pt-lg-0 mt--100">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-12">
            <div class="row row-grid">
            {% for post in posts %}
              <div class="col-lg-3">
                <div class="card card-lift--hover shadow border-0">
                  <div class="card-header">
                    <img src="{% if post.image_card %}{{post.image_card.url}}{%else%}{%static 'img/brand/Logo-morral-1.png'%}{%endif%}"  class="img-fluid">
                  </div>
                  <div class="card-body py-5">
                    <h6 class="text-warning text-uppercase">{{post.title}}</h6>
                    <!--<p class="description mt-3">{{post.description|truncatewords_html:10}}</p>-->
                    <div>
                    {% for tag in post.tags.all %}  
                      <a href="{% url 'blog:post_list_by_tag' tag.slug %}"><span class="badge badge-pill badge-warning"><i class="fas fa-tag"></i> {{ tag.name }}</span></a>
                      {% if not forloop.last %}, {% endif %}
                    {% endfor %}
                    </div>
                    <a href="{{post.get_absolute_url}}" class="btn btn-warning mt-4">LEER</a>
                  </div>
                </div>
              </div>
            {% endfor %}
            </div>
          </div>
        </div>
        <div class="pt-lg-0 my-3">
            {% include "blog/pagination.html" with page=posts %}
        </div>
      </div>
    </section>
{% endblock content %}

blog/templates/blog/publicaciones_comentadas.html
{% load blog_tags %}

<div class="container" style="padding: 30px;">
	<h2 class="text-center title">Blog - Entradas Destacadas</h2>
	<hr>
	{% get_most_commented_posts as most_commented_posts %}
    {% for post in most_commented_posts %}
	{% if forloop.first %}
	<div class="row" style="padding-top: 3px;">
	{%endif%}
		<div class="col-lg-3 col-md-4 col-sm-6 text-center">
			<div class="card bordesito" style="width: 17rem;">
			  <img class="card-img-top" src="{{post.portada.url}}" alt="Teotihuacán Mágico" width="50" height="150">
			  <div class="card-block">
			    <h4 class="card-title title-card text-center">{{post.title|truncatewords_html:3}}</h4>
			    
			   </div>
			    <a href="{{post.get_absolute_url}}" class="btn btn-danger">Leer</a>
			</div>
		</div>
		{% if forloop.counter|divisibleby:4 %}
		</div><div class="row">
		{% endif %}            
	    {% if forloop.last %}
	        </div>
	    {% endif %}
	{%endfor%}
	</div>
</div>