MorralViajero/urls.py
from django.conf.urls import url,include
from django.contrib import admin

from main import urls as UrlMain
from travels import urls as UrlTravel
from blog import urls as UrlBlog

from django.views.static import serve
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(UrlMain, namespace="main")),
    url(r'^', include(UrlTravel, namespace="travel")),
    url(r'^blog/', include(UrlBlog, namespace="blog")),
    #Url para media
    url(
    	regex=r'^media/(?P<path>.*)$',
    	view=serve,
    	kwargs = {'document_root':settings.MEDIA_ROOT}),
]

blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.PostList.as_view(), name='post_list'),
	url(r'^tag/(?P<tag_slug>[-\w]+)/$', views.PostList.as_view(), name="post_list_by_tag"),
	url(r'^list/$', views.PostListView.as_view(), name='post_list_view'),
	url(r'^(?P<post>[-\w]+)/$', views.PostDetailView.as_view(), name="post_detail"),
	url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$', views.PostDetail.as_view(), name="post_detail"),
	url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/(?P<ready>\d+)/$', views.PostDetail.as_view(), name="post_detail_ready"),
	url(r'^(?P<post_id>\d+)/share/$', views.SentEmailView.as_view(), name="post_share"),
	url(r'^(?P<post_id>\d+)/(?P<conf>\d+)/share/$', views.SentEmailView.as_view(), name="post_share_conf"),
]

main/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$',views.MainView.as_view(), name = "main"),
	url(r'^registro/$',views.RegisterView.as_view(), name = "register"),
	url(r'^terminos-y-condiciones/$',views.TermsAndConditionsView.as_view(), name = "terms"),
	url(r'^nosotros/$',views.AboutUsView.as_view(), name = "about"),
]

travels/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^travels/$', views.Travel_List.as_view(),name="travel_list"),
    url(r'^travel/(?P<slug>[-\w]+)/$',views.Travel_Detail.as_view(), name="travel_detail"),
    url(r'^travels-by-category/(?P<category_slug>[-\w]+)/$',views.Travel_List.as_view(),name="travels_by_category"),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
{% load blog_tags %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Morral Viajero</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta content="" name="Morral Viajero"/>
    <!--Facebook-->
    <meta property="og:url"           content="wwww.morralviajero.com" />
    <meta property="og:type"          content="article" />
    <meta property="og:title"         content="Morral Viajero" />
    <meta property="og:description"   content="agencia de viajes" />
    <meta property="og:image"         content="http:/wwww.morralviajero.com/static/img/log-nav-mv.png" />
    
    <!-- Facebook Pixel Code -->
    <script>
      !function(f,b,e,v,n,t,s)
      {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
      n.callMethod.apply(n,arguments):n.queue.push(arguments)};
      if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
      n.queue=[];t=b.createElement(e);t.async=!0;
      t.src=v;s=b.getElementsByTagName(e)[0];
      s.parentNode.insertBefore(t,s)}(window, document,'script',
      'https://connect.facebook.net/en_US/fbevents.js');
      fbq('init', '2246024605627759');
      fbq('track', 'PageView');

    </script>
    <noscript><img height="1" width="1" style="display:none"
      src="https://www.facebook.com/tr?id=2246024605627759&ev=PageView&noscript=1"
    /></noscript>
    <!-- End Facebook Pixel Code -->

    <!--Google adsense-->
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <script>
      (adsbygoogle = window.adsbygoogle || []).push({
        google_ad_client: "ca-pub-6548195668340121",
        enable_page_level_ads: true
      });
    </script>

  	<!-- Favicon -->
  	<link href="{% static 'img/log-nav-mv.png' %}" rel="icon" type="image/png">
  	<!-- Fonts -->
  	<link href="https://fonts.googleapis.com/css?family=Dosis" rel="stylesheet">
  	
  	
  	<!--  CSS -->
    {% if DEBUG %}
      <link type="text/css" href="{% static 'css/styles.css' %}" rel="stylesheet">
      {% else %}
      <link type="text/css" href="{% static 'css/argon.css' %}" rel="stylesheet">
      <link type="text/css" href="{% static 'css/mv.css' %}" rel="stylesheet">
    {% endif %}

  	<!--  CSS -->
  	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">

    {% block head %}
      
      {% block fb_pixel %}
        
      {% endblock fb_pixel %}

    {% endblock head %}


</head>
<body>
  <header class="header-global">
    <nav id="navbar-main" class="navbar navbar-main navbar-expand-lg navbar-transparent navbar-light">
      <div class="container">
        <a class="navbar-brand mr-lg-4" href="{% url 'main:main' %}">
          <img src="{% static 'img/brand/Logo-morral-1.png' %}">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar_global" aria-controls="navbar_global" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse" id="navbar_global">
          <div class="navbar-collapse-header">
            <div class="row">
              <div class="col-6 collapse-brand">
                <a href="{% url 'main:main' %}">
                  <img src="{% static 'img/brand/Logo-morral-1.png' %}">
                </a>
              </div>
              <div class="col-6 collapse-close">
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar_global" aria-controls="navbar_global" aria-expanded="false" aria-label="Toggle navigation">
                  <span></span>
                  <span></span>
                </button>
              </div>
            </div>
          </div>
          <ul class="navbar-nav navbar-nav-hover align-items-lg-center">
            <li class="nav-item dropdown">
              <a href="{% url 'travel:travel_list' %}" class="nav-link"  role="button">
                <i class="ni ni-ui-04 d-lg-none"></i>
                <span class="nav-link-inner--text">Mochilazos</span>
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'blog:post_list' %}" class="nav-link"  role="button">
                <i class="ni ni-collection d-lg-none"></i>
                <span class="nav-link-inner--text">Blog</span>
              </a>
            </li>
          </ul>
          <ul class="navbar-nav align-items-lg-center ml-lg-auto">
            <li class="nav-item">
              <a class="nav-link nav-link-icon" href="https://www.facebook.com/morralviajero" target="_blank" data-toggle="tooltip" title="Like us on Facebook">
                <i class="fab fa-facebook"></i>
                <span class="nav-link-inner--text d-lg-none">Facebook</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link nav-link-icon" href="https://www.instagram.com/morralviajero22" target="_blank" data-toggle="tooltip" title="Follow us on Instagram">
                <i class="fab fa-instagram"></i>
                <span class="nav-link-inner--text d-lg-none">Instagram</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link nav-link-icon" href="https://www.youtube.com/channel/UCW2SG2wH_PC0-cgJXSnCnUA" target="_blank" data-toggle="tooltip" title="Follow us on Youtube">
                <i class="fab fa-youtube"></i>
                <span class="nav-link-inner--text d-lg-none">Youtube</span>
              </a>
            </li>
            <!--<li class="nav-item d-none d-lg-block ml-lg-4">
              <a href="{% url 'main:register' %}" class="btn btn-neutral btn-icon">
                <span class="btn-inner--icon">
                  <i class="fa fa-cloud-download mr-2"></i>
                </span>
                <span class="nav-link-inner--text">Registrate</span>
              </a>
            </li> -->
          </ul>
        </div>
      </div>
    </nav>
  </header>

  {% block content %} 

  {% endblock content %}


  <!-- Load Facebook SDK for JavaScript -->
  <div id="fb-root"></div>
  <script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = 'https://connect.facebook.net/es_LA/sdk/xfbml.customerchat.js#xfbml=1&version=v2.12&autoLogAppEvents=1';
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>

  <!-- Your customer chat code -->
  <div class="fb-customerchat"
    attribution=setup_tool
    page_id="790299671174582"
    theme_color="#44bec7"
    logged_in_greeting="¡Hola Viajero! ¿En qué podemos ayudarte?"
    logged_out_greeting="¡Hola Viajero! ¿En qué podemos ayudarte?">
  </div>
  
  <footer class="footer has-cards">
    <div class="container container-lg">
      {% show_latest_posts 4%}
    </div>
    <div class="container">
      <div class="row row-grid align-items-center my-md">
        <div class="col-lg-6">
          <h3 class="text-info font-weight-light mb-2">¡Siguenos en Redes Sociales!</h3>
          <h4 class="mb-0 font-weight-light">y descubre la experiencia de ser un #mochilero.</h4>
        </div>
        <div class="col-lg-6 text-lg-center btn-wrapper">
          <a target="_blank" href="https://www.facebook.com/morralviajero" class="btn btn-neutral btn-icon-only btn-facebook btn-round btn-lg" data-toggle="tooltip" data-original-title="Like on Facebook">
            <i class="fab fa-facebook"></i>
          </a>
          <a target="_blank" href="https://www.youtube.com/channel/UCW2SG2wH_PC0-cgJXSnCnUA" class="btn btn-neutral btn-icon-only btn-youtube btn-lg btn-round" data-toggle="tooltip" data-original-title="Suscribirse">
            <i class="fab fa-youtube"></i>
          </a>
          <a target="_blank" href="https://twitter.com/MorralViajero" class="btn btn-neutral btn-icon-only btn-twitter btn-lg btn-round" data-toggle="tooltip" data-original-title="Follow us">
            <i class="fab fa-twitter"></i>
          </a>
          <a target="_blank" href="https://www.instagram.com/morralviajero22" class="btn btn-neutral btn-icon-only btn-instagram btn-round btn-lg" data-toggle="tooltip" data-original-title="Follow on Instagram">
            <i class="fab fa-instagram"></i>
          </a>
        </div>
      </div>
      <hr>
      <div class="row align-items-center justify-content-md-between">
        <div class="col-md-6">
          <div class="copyright">
            &copy; 2018
            <a href="#" target="_blank">Morral Viajero</a>.
          </div>
        </div>
        <div class="col-md-6">
          <ul class="nav nav-footer justify-content-end">
            <li class="nav-item">
              <a href="{% url 'main:terms' %}" class="nav-link">Términos y condiciones</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'main:about' %}" class="nav-link">Nosotros</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'blog:post_list' %}" class="nav-link">Blog</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </footer>

  {% block scripts %}
	
  {% endblock scripts %}

  <!-- Core -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/popper/popper.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/bootstrap.min.js' %}"></script>
  <script src="{% static 'vendor/headroom/headroom.min.js' %}"></script>
  <!-- Argon JS -->
  {% if DEBUG %}
  <script src="{% static 'js/argon.js' %}"></script>
    {% else %}
    <script src="{% static 'js/argon.min.js' %}"></script>
  {%endif%}
  <!--Markdown-->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.5/marked.min.js"></script>
  

  <script type="text/javascript">
    $(document).ready(function(){
      $(".content-markdown").each(function(){
        /*var content = $(this).text()
        console.log(content)
        var markedContent = marked(content)
        console.log(markedContent)
        $(this).html(markedContent)*/
      })
      $(".content-markdown img").each(function(){
        $(this).addClass("img-fluid")        
      })
    })
  </script>
  <!-- Load Facebook SDK for JavaScript -->
  <div id="fb-root"></div>
  <script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.0";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>

</body>

</html>